### ISSUE TITLE
Upload does not work

### ISSUE THREAD

**Issue by niketkanoi-amersports** [cringdahl/sharepoint-file-upload-action#10]
`Run cringdahl/sharepoint-file-upload-action@v1.1.0
/usr/bin/docker run --name f57f477078f1df93c5415ab6507a48a7eccefa_f86b96 --label f57f47 --workdir /github/workspace --rm -e "INPUT_FILE_PATH" -e "INPUT_HOST_NAME" -e "INPUT_SITE_NAME" -e "INPUT_UPLOAD_PATH" -e "INPUT_TENANT_ID" -e "INPUT_CLIENT_ID" -e "INPUT_CLIENT_SECRET" -e "INPUT_MAX_RETRIES" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/xxxxxxxxxxxxxxxxxx":"/github/workspace" f57f47:7078f1df93c5415ab6507a48a7eccefa  "xxxxxxxxxxxxxxxxxx" "xxxxxxxxxxxxxxxxxx" "xxxxxxxxxxxxxxxxxx" "xxxxxxxxxxxxxxxxxx" "***" "xxxxxxxxxxxxxxxxxx" "/tmp/foo.txt" "3"`

This is the only output we see for the step completion. No files were transferred to Sharepoint. Is there a way to find what is the error due to which files were not transferred? Sensitive info has been xxxx out.

**Comment by cringdahl** [comment]
I'm afraid I'm no longer working at a company with Sharepoint access, so I can't troubleshoot anymore.
