### ISSUE TITLE
Document how to setup credentials

### ISSUE THREAD

**Issue by gionn** [cringdahl/sharepoint-file-upload-action#11]
Hello,

I understood the first step is to [register an application](https://learn.microsoft.com/en-us/graph/auth-register-app-v2) and obtain the 3 requested credentials (tenant-id, client-id and client-secret) as documented also in [msgraph-sdk-python](https://github.com/microsoftgraph/msgraph-sdk-python).

Then (and this would be super-helpful to have documented) I guess we need to [assign some permissions to the application](https://learn.microsoft.com/en-us/graph/auth-v2-service?tabs=http#step-1-configure-permissions-for-microsoft-graph) choosing between the [available permissions](https://learn.microsoft.com/en-us/graph/permissions-reference), which I guess is enough for this action to have `Files.ReadWrite.All` or even better `Files.SelectedOperations.Selected` to retrict to a specific site/operations?

**Comment by cringdahl** [comment]
When I worked at the company that had Sharepoint access, the permission assignment was handled by a separate group. When you figure out steps for permission assignment, please put in a documentation PR.
