### ISSUE TITLE
Support > 250MB upload or add error/warning if > 250MB.

### ISSUE THREAD

**Issue by ETdoFresh** [cringdahl/sharepoint-file-upload-action#2]
I thought I was doing something wrong setting up this github action on my repo trying to upload a big file (3GB+). It would just timeout after 5ish hours. After several attempts, I decided to look at the code and noticed it was using Microsoft Graph. I then started to look through its documentation, and...

I believe [drive.upload_file(...)](https://github.com/cringdahl/sharepoint-file-upload-action/blob/93fcdba5086b934a6864f28e4f3101c0dcf6643a/src/send_to_sharepoint.py#L38) only [supports <= 250MB](https://learn.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=http).

Would it be possible to support > 250MB? If not could you put an error or warning for future users who try to upload and get no message? Thank you very much!

Here are some resources to help support > 250MB:
- https://learn.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0
- https://learn.microsoft.com/en-us/graph/sdks/large-file-upload?tabs=csharp
- https://stackoverflow.com/questions/56270467/uploading-huge-files-into-onedrive-using-sdk
- https://github.com/O365/python-o365/issues/337
- https://youtu.be/blBmU8VISBQ?si=tD5_GHFV-j6lIvv-

**Comment by ETdoFresh** [comment]
Ooo, it's only 4MB? looking at the python library now...

https://github.com/vgrem/Office365-REST-Python-Client/blob/159755fc3fbeb1efe26c2310ebf361c35ffb9f00/office365/onedrive/driveitems/driveItem.py#L241

**Comment by cringdahl** [comment]
> Ooo, it's only 4MB? looking at the python library now...
> 

Yeah, this was only ever originally meant to send a few small reports to a OneDrive, not manage DVD ISOs or anything. Thanks for contributing!
