### ISSUE TITLE
Authentication issues

### ISSUE THREAD

**Issue by LukeHersman** [cringdahl/sharepoint-file-upload-action#5]
Trying out this action and ran into some authentication issues. I had my sharepoint admin create an app registration in azure portal for sharepoint and got the two IDs and secret, but when I tried to use I got the following error:

```
Unexpected error occurred: ('AccessDenied', 'Either scp or roles claim need to be present in the token.', '403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0/sites/{company}.sharepoint.com:/sites/{sitename}'), <class 'office365.runtime.client_request_exception.ClientRequestException'>
Traceback (most recent call last):
```
It could be a issue with the secret because the sharepoint admin had never done this before and I was trying to talk them through it but I wasn't really sure the correct way to do that either since Im not admin and couldn't see the screen.

**Comment by cringdahl** [comment]
I'm afraid I didn't set up any of the Entra app that was assigned to me, so I can't give any insights there. However, it looks pretty barebones. One thing my admin did was assign ownership and admin rights of the App registration to me (so I'd be able to refresh secrets and so on). Perhaps your admin could do the same?

**Comment by rustymyers** [comment]
I'm having the same issue. Our app needs to allow permissions on the Sharepoint site. Looking to add this, but I'm not sure what is exactly needed: https://devblogs.microsoft.com/microsoft365dev/updates-on-controlling-app-specific-access-on-specific-sharepoint-sites-sites-selected/
