### ISSUE TITLE
  API endpoints for need to be variablized to allow for proper Soverign Cloud Use of action

### ISSUE THREAD

**Issue by pappasjfed** [cringdahl/sharepoint-file-upload-action#6]
The endpoints for sovereign clouds need to be changed or variablized to allow for proper functionality.

_Example_:
Commercial/worldwide endpoints:
https://login.microsoftonline.com/
https://graph.microsoft.com/
 
These need to be changed if the SharePoint is in the _US Sovereign_ cloud:
https://login.microsoftonline.us/
https://graph.microsoft.us/

I don't know if only the TLD country code changes (.COM -> .US) or if the full endpoint should be variables.

I like the idea of default being commercial and being able to override explicitly.

Impacts code in `src/send_to_sharepoint.py` lines 32 and 38.

**Comment by pappasjfed** [comment]
Submitted PR to variablize the endpoints.  I cannot test the changes yet as I am still waiting for my app info for using this "app"

**Comment by cringdahl** [comment]
And merged.
